import { ArrowRight,ArrowLeftRight,MessageCircle,Sparkles,Heart,ShieldCheck,Mic,Camera,Code,Check } from "lucide-react";
import cue from "../../../mobile/assets/images/davaq/queue.png";
import "./davaq.css";
const app="/app/";
export default function Home(){
 return <main className="dq-site"><div className="dq-shell"><header className="dq-nav"><a href="/" className="dq-brand">DavaQ<span>다바꿔</span></a><nav><a href="#how">어떻게 바꾸나요?</a><a href={app} className="dq-pill">시작하기 <ArrowRight size={16}/></a></nav></header>
 <section className="dq-hero"><div className="dq-copy"><div className="dq-eyebrow"><span/> AI와 함께하는 경험 교환</div><h1>말 한마디로,<br/>경험이 <em>바뀌는 곳.</em></h1><p>내가 줄 수 있는 것과 받고 싶은 것을 말해보세요.<br className="dq-desktop"/>나의 AI 큐가 서로 맞는 상대를 찾아주고,<br className="dq-desktop"/>채팅으로 새로운 교환을 시작해요.</p><a className="dq-primary" href={app}>나의 첫 교환 시작하기 <ArrowRight size={20}/></a><div className="dq-caption">물건 · 재능 · 시간 · 경험, 현금 없이 다 바꿔요.</div></div><div className="dq-scene"><div className="dq-orbit"/><div className="dq-speech"><Sparkles size={18}/> 오늘은 무엇을 바꿔볼까요?</div><img className="dq-cue" src={cue} alt="나의 AI 파트너 큐"/><div className="dq-floating dq-give"><span className="dq-icon"><Mic size={22}/></span><div><small>내가 줄 수 있는 것</small><strong>나만의 목소리 수업</strong></div></div><div className="dq-floating dq-want"><span className="dq-icon mint"><Camera size={22}/></span><div><small>받고 싶은 경험</small><strong>새로운 나를 담는 사진</strong></div></div><span className="dq-example">교환 아이디어 예시</span></div></section>
 <section id="how" className="dq-section"><div className="dq-eyebrow">A LITTLE GIVE. A NEW EXPERIENCE.</div><h2>내가 가진 하나가,<br/>누군가의 새로운 시작이 돼요.</h2><div className="dq-steps">{[{n:"01",icon:MessageCircle,title:"편하게 말해요",body:"잘하는 일 하나, 나누고 싶은 물건 하나. 큐가 대화를 교환 등록 초안으로 정리해요."},{n:"02",icon:Sparkles,title:"서로 맞는 연결을 찾아요",body:"희망 분야와 지역, 가능한 요일을 살피고 내가 확인한 취향을 추천에 반영해요."},{n:"03",icon:ArrowLeftRight,title:"채팅으로 함께 정해요",body:"제공 범위와 일정을 확인하고 양쪽이 동의하면 예약 완료. 서로 받은 뒤 교환을 마무리해요."}].map(({n,icon:Icon,title,body})=><article key={n}><span className="dq-step-no">{n}</span><Icon size={30}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="dq-growth"><div className="dq-growth-visual"><img src={cue} alt="" loading="lazy"/><div className="dq-milestones"><span><Check size={16}/> 첫 만남</span><span><Heart size={16}/> 취향 발견</span><span><Sparkles size={16}/> 첫 교환</span></div></div><div><div className="dq-eyebrow">MEET YOUR 큐</div><h2>함께할수록,<br/>나를 더 잘 아는 파트너.</h2><p>큐에게 취향을 알려주고, 새로운 경험을 나눠보세요. 확인한 기억과 실제 교환이 큐의 성장으로 남아요.</p><ul><li><Check size={17}/> 내가 확인한 기억으로 더 잘 맞는 추천</li><li><Check size={17}/> 선택한 대화에서 내 메시지만 학습</li><li><Check size={17}/> 기억 수정·삭제, 학습 중지까지 직접</li></ul><a href={app}>나의 큐 만나기 <ArrowRight size={18}/></a></div></section>
 <section className="dq-section"><div className="dq-section-heading"><div><div className="dq-eyebrow">EXCHANGE YOUR POSSIBILITIES</div><h2>이런 교환, 상상해봤나요?</h2></div><span>등록 가능한 아이디어 예시</span></div><div className="dq-examples">{[{icon:Mic,title:"목소리로 전하는 자신감",give:"발성·프레젠테이션 코칭",want:"프로필 사진 촬영",tone:"violet"},{icon:Code,title:"나의 재능, 새로운 취미로",give:"웹사이트 제작 도움",want:"기타 입문 수업",tone:"peach"},{icon:Heart,title:"나누면 더 커지는 경험",give:"사업 경험 멘토링",want:"브랜드 디자인",tone:"mint"}].map(({icon:Icon,title,give,want,tone})=><a href={app} className={"dq-ex-card "+tone} key={title}><Icon size={34}/><h3>{title}</h3><p>{give}</p><span><ArrowLeftRight size={17}/>{want}</span><ArrowRight className="dq-card-arrow" size={22}/></a>)}</div></section>
 <section className="dq-trust"><ShieldCheck size={32}/><div><h3>추천은 큐가, 결정은 내가.</h3><p>등록 공개, 제안 전송, 교환 확정은 직접 확인해요. EV는 서로의 희망 교환가치를 비교하는 참고값이에요.</p></div></section>
 <section className="dq-final"><div className="dq-eyebrow">YOUR NEXT EXPERIENCE STARTS HERE</div><h2>오늘, 무엇을 바꿔볼까요?</h2><a href={app} className="dq-primary">DavaQ 시작하기 <ArrowRight size={20}/></a><p>모바일과 PC에서 바로 시작할 수 있어요.<br/>휴대폰 브라우저에서 홈 화면에 추가하면 더 편리해요.</p></section>
 <footer><a href="/" className="dq-brand">DavaQ</a><span>경험이 이어지는, 더 특별한 하루.</span><span>© {new Date().getFullYear()} DavaQ</span></footer></div></main>;
}
